version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init-dev.sql:/docker-entrypoint-initdb.d/init.sql # runs once on first start

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
      PORT: 4000
    ports:
      - "4000:4000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"   # nginx serves at port 80 inside container, mapped to 3000 locally
    depends_on:
      - backend
    volumes:
      - ./frontend/build:/usr/share/nginx/html

volumes:
  pgdata:
