export { default as Navbar } from '../components/nav/Navbar'
export { default as Mainheader } from '../components/nav/Mainheader'
export { default as Header } from '../components/nav/Header'
export { default as Hero } from './hero/Hero'
export { default as Jobs } from '../components/jobs/Jobs'
export { default as Footer } from '../components/Footer'
export { default as Meetandplay } from '../components/Meetandplay'
export { default as SportVirtual } from '../components/SportVirtual'
export { default as Meetandplayapp } from '../components/Meetandplayapp'
export { default as Tennisandpadelinfo } from '../components/Tennisandpadelinfo'
export { default as Eachevent } from '../components/Eachevent'
export { default as LoginSignup } from '../components/loginandsignup/LoginSignup'
export { default as Partners } from '../components/Partners'
export { default as Usefullinks } from '../components/Usefullinks'
export { default as Latestnews } from './Latestnews/Latestnews'


